### ISSUE TITLE
AdoptOpenJDK API version 2 is deprecated

### ISSUE THREAD

**Issue by JamesBlandford** [cloudfoundry/ibm-websphere-liberty-buildpack#465]
We need to upgrade the OpenJ9 endpoints to point at "v3" not "v2"

this is causing me issues trying to use Java 9 because it's pointed at a URL which 404s

Java 11 works properly, as the following:

https://api.adoptopenjdk.net/v2/info/releases/openjdk9?openjdk_impl=openj9&type=jre&arch=x64&os=linux&heap_size=normal Doesnt Work

https://api.adoptopenjdk.net/v2/info/releases/openjdk11?openjdk_impl=openj9&type=jre&arch=x64&os=linux&heap_size=normal Works

**Comment by kevin-ortega** [comment]
@JamesBlandford I created a branch that supports v3 but Java 9 still does not work.  
Following the V3 API and using the [Swagger UI](https://api.adoptopenjdk.net/swagger-ui/), querying Java 9 and Java 10 returns 404:
https://api.adoptopenjdk.net/v3/assets/feature_releases/9/ga?architecture=x64&heap_size=normal&image_type=jre&jvm_impl=openj9&os=linux&vendor=adoptopenjdk

https://api.adoptopenjdk.net/v3/assets/feature_releases/10/ga?architecture=x64&heap_size=normal&image_type=jre&jvm_impl=openj9&os=linux&vendor=adoptopenjdk

However, querying Java 8, 11, 12 returns a list:
https://api.adoptopenjdk.net/v3/assets/feature_releases/8/ga?architecture=x64&heap_size=normal&image_type=jre&jvm_impl=openj9&os=linux&vendor=adoptopenjdk

https://api.adoptopenjdk.net/v3/assets/feature_releases/11/ga?architecture=x64&heap_size=normal&image_type=jre&jvm_impl=openj9&os=linux&vendor=adoptopenjdk

https://api.adoptopenjdk.net/v3/assets/feature_releases/12/ga?architecture=x64&heap_size=normal&image_type=jre&jvm_impl=openj9&os=linux&vendor=adoptopenjdk

I will merge the branch that supports V3 but something needs to be fixed with the API.

**Comment by kevin-ortega** [comment]
Using V2 API is not the issue.  Both V2 and V3 API return 404 when querying Java 9.   Since V2 has been deprecated I have migrated the buildpack to use V3 instead.
